### ISSUE TITLE
We need more cats

### ISSUE THREAD

**Issue by flipbagels** [aavashsubedi/oxrse_unit_conv#2]
### Name (Abbreviation) of the unit you want to create?

cats

### What is its base SI unit?

ca

### Would you like to provide more information about your unit?

we need cat units to bring joy in the world

### Contributor Guide

- [x] I will comply with the [Contributor Guide](../../CONTRIBUTING.md)

### Code of Conduct

- [X] I have read and agree to the project's [Code of Conduct](../../CODE_OF_CONDUCT.md)

**Comment by aavashsubedi** [comment]
I do
